3.00

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1311,9 +1311,9 @@ CONFIGDIR=${srcdir}/tclconfig
 
 PACKAGE=mysqltcl
 
-MAJOR_VERSION=2
-MINOR_VERSION=5
-PATCHLEVEL=1
+MAJOR_VERSION=3
+MINOR_VERSION=0
+PATCHLEVEL=0
 
 VERSION=${MAJOR_VERSION}.${MINOR_VERSION}${PATCHLEVEL}
 NODOT_VERSION=${MAJOR_VERSION}${MINOR_VERSION}
@@ -8183,9 +8183,6 @@ else
 fi;
 MYSQL_INCLUDES="-I$MYSQL_INC_DIR"
 
-if test ! -f $MSQL_LIB_DIR/libmysqlclient${SHLIB_SUFFIX} -a -f /usr/lib/libmysqlclient${SHLIB_SUFFIX}; then
-   MYSQL_LIB_DIR=/usr/lib
-fi
 
 # Check whether --enable-mysqlstatic or --disable-mysqlstatic was given.
 if test "${enable_mysqlstatic+set}" = set; then
@@ -8198,6 +8195,9 @@ fi;
 if test "$tcl_ok" = "yes"; then
    LIBS="${LIBS} ${MYSQL_LIB_DIR}/libmysqlclient.a -lz -lcrypt -lnsl -lm"
 else
+   if test ! -f $MSQL_LIB_DIR/libmysqlclient${SHLIB_SUFFIX} -a -f /usr/lib/libmysqlclient${SHLIB_SUFFIX}; then
+      MYSQL_LIB_DIR=/usr/lib
+   fi
    MYSQL_LIBS="-L$MYSQL_LIB_DIR -lmysqlclient"
    if test ! "$MYSQL_LIB_DIR" = ""; then
      LIBMYSQL="libmysqclient${SHLIB_SUFFIX}"
@@ -8220,10 +8220,18 @@ echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 echo "$as_me:$LINENO: checking for libmysqlclient lib" >&5
 echo $ECHO_N "checking for libmysqlclient lib... $ECHO_C" >&6
-if test ! -f ${MYSQL_LIB_DIR}/libmysqlclient${SHLIB_SUFFIX} ; then
-   { { echo "$as_me:$LINENO: error: Cannot find libmysqlclient${SHLIB_SUFFIX} in $MYSQL_LIB_DIR use -with-mysql-lib=?" >&5
+if test "$tcl_ok" = "yes"; then
+   if test ! -f ${MYSQL_LIB_DIR}/libmysqlclient.a ; then
+   	{ { echo "$as_me:$LINENO: error: Cannot find libmysqlclient.a in $MYSQL_LIB_DIR use -with-mysql-lib=?" >&5
+echo "$as_me: error: Cannot find libmysqlclient.a in $MYSQL_LIB_DIR use -with-mysql-lib=?" >&2;}
+   { (exit 1); exit 1; }; }
+   fi
+else
+   if test ! -f ${MYSQL_LIB_DIR}/libmysqlclient${SHLIB_SUFFIX} ; then
+   	{ { echo "$as_me:$LINENO: error: Cannot find libmysqlclient${SHLIB_SUFFIX} in $MYSQL_LIB_DIR use -with-mysql-lib=?" >&5
 echo "$as_me: error: Cannot find libmysqlclient${SHLIB_SUFFIX} in $MYSQL_LIB_DIR use -with-mysql-lib=?" >&2;}
    { (exit 1); exit 1; }; }
+   fi
 fi
 echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
